### ISSUE TITLE
Where to place reviewers.config exactly ?

### ISSUE THREAD

**Issue by smirn0v** [davido/gerrit-reviewers-plugin#1]
First of all – thank you for your great work.

Documentation doesn't seems to be exhaustive describing where should 'reviewers.config' file be placed.

What have I tried:
- ./gerrit-site-dir/etc/reviewers.config
- special branch 'meta/config' with ./reviewers.config inside the root folder

Contents of the file were the same

```
[filter "*"]
    reviewer = someone
```

Not a one attempt ended up successfully. No errors inside "errors_log" though.
Could you please provide a bit more information where should 'reviewers.config' be placed ?

**Comment by pplmx** [comment]
The file should be named `reviewers`???
I see this 
> https://gerrit.googlesource.com/plugins/reviewers/+doc/master/src/main/resources/Documentation/config.md
> Global configuration of the @PLUGIN@ plugin is done in the `reviewers.config` file in the site's etc directory.

The doc is still `reviewers.config`. Which one is right?
