### ISSUE TITLE
Where to file bugs or ask for help?

### ISSUE THREAD

**Issue by snakescott** [davido/gerrit-reviewers-plugin#2]
I realize the project has moved to https://gerrit.googlesource.com/plugins/reviewers/, but Google Git doesn't seem to have an issue tracker, etc?

It looks like Gerrit issues live at https://code.google.com/p/gerrit/issues/list , is that the right place to file gerrit-reviewers-plugin issues as well?

**Comment by davido** [comment]
Yes. This is the correct isue tracker for the time being. Just use [reviewer] or some such prefix in the subject.

**Comment by davido** [comment]
I also modified the repository description.

**Comment by snakescott** [comment]
Great, thanks!
